[from-pjsip]
; Ramal 500 chama o LiveKit SIP
exten => 500,1,NoOp(Enviando chamada para LiveKit SIP)
 same => n,Dial(PJSIP/500@livekit_trunk,60)
 same => n,Hangup()

; Teste de echo local no Asterisk
exten => 600,1,Answer()
 same => n,Echo()
 same => n,Hangup()