[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060



; ==========================
; AUTH RAMAL 9000
; ==========================
[auth9000]
type=auth
auth_type=userpass
username=9000
password=Senha9000

; ==========================
; AOR RAMAL 9000
; ==========================
[9000]
type=aor
max_contacts=1
remove_existing=yes

; ==========================
; ENDPOINT RAMAL 9000
; ==========================
[9000]
type=endpoint
aors=9000
auth=auth9000
context=from-pjsip
disallow=all
allow=ulaw,alaw
direct_media=no
transport=transport-udp
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes

; ==========================
; TRUNK PARA LIVEKIT SIP
; ==========================
[livekit_trunk]
type=endpoint
transport=transport-udp
context=from-livekit
disallow=all
allow=ulaw
aors=livekit_trunk
direct_media=no

[livekit_trunk]
type=aor
contact=sip:livekit-sip:5061
