[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[livekit-sip]
type=endpoint
transport=transport-udp
context=from-livekit
disallow=all
allow=ulaw
allow=alaw
aors=livekit-sip
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[livekit-sip]
type=aor
contact=sip:192.168.0.100:5060

[livekit-sip-identify]
type=identify
endpoint=livekit-sip
match=192.168.0.100
